apiVersion: apps/v1
kind: Deployment
metadata:
  name: "react-ui"
  namespace: ms
  labels:
    app: "react-ui"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "react-ui"
  strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: "react-ui"
    spec:
      containers:
      - name: "react-ui"
        image: deekshithsn/ui
       ports:
        - containerPort: 8080
          name: "react-ui"
        
      
